### ISSUE TITLE
Exceptions occurred when Chat parsed Standard_chat_message

### ISSUE THREAD

**Issue by jstzwj** [dotnetGame/MineCase#17]
StackTrace
Invalid cast from 'System.Int64' to 'MineCase.Formats.HoverEventType'.
 at Newtonsoft.Json.Linq.Extensions.Convert[T,U](T token)
   at MineCase.Formats.Chat.ConstructCommonPart(JObject jsonObject, ChatComponent component) in C:\MineCase\src\MineCase.Protocol\Formats\Chat.cs:line 724
   at MineCase.Formats.Chat.ParseCompoent(JObject jsonObject) in C:\MineCase\src\MineCase.Protocol\Formats\Chat.cs:line 673
   at MineCase.Formats.Chat.ParseCompoent(JObject jsonObject) in C:\MineCase\src\MineCase.Protocol\Formats\Chat.cs:line 658
   at MineCase.Formats.Chat.Parse(String json) in C:\MineCase\src\MineCase.Protocol\Formats\Chat.cs:line 602

http://wiki.vg/Chat#Standard_chat_message

**Comment by Alinshans** [comment]
This bug has been fixed, see #16
